all: build

SI_SPEC := scheduler-interface-spec.md
SI_PROTO := si.proto

# generate the proto file from the spec
$(SI_PROTO).tmp: $(SI_SPEC)
	echo "// **** DO NOT EDIT\n// **** This code is generated by the buikd process.\n// **** DO NOT EDIT" > $@
	cat $< | sed -n -e '/```protobuf$$/,/^```$$/ p' | sed '/^```/d' >> $@
	awk '{ if (length > 200) print NR, $$0 }' $@ | diff - /dev/null
	(diff $@ $(SI_PROTO) > /dev/null 2>&1 || mv -f $@ $(SI_PROTO)) && \
		rm -f $@

# main build first check the input then generate
build: $(SI_PROTO).tmp
	$(MAKE) -C lib/go

# simple clean of generated files only
clean:
	$(MAKE) -C lib/go $@

# remove all non versioned files
# will require a re-install of protoc etc in te next cycle
clobber:
	$(MAKE) -C lib/go $@

.PHONY: clean clobber check
