name: Pre-commit checks

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: .go_version
      - name: Check license
        run: make license-check
      - name: Build and Check for changes
        run: make check
