name: Pre-commit checks

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Check license
        run: make license-check
        if: ${{ github.event_name == 'pull_request' }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: .go_version
      - name: Run build
        run: make 
