name: Pre-commit checks

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: Run Makefile
        run: make 
